### ISSUE TITLE
feat: automatically open PR to update standalone on notification of pact-ruby-standalone release

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/homebrew-pact-ruby-standalone#20]
As per the pact-node one https://github.com/pact-foundation/pact-node/blob/master/.github/workflows/update.yml

**Comment by surpher** [comment]
@bethesque the workflow is ready at https://github.com/pact-foundation/homebrew-pact-ruby-standalone/blob/master/.github/workflows/update.yml

The missing piece is adding the `GITHUB_TOKEN`. I do not have the rights in this repo to add it. Counting on you to sort out this `${{ secret.GITHUB_TOKEN }}`.

Few things left to do:
1. Set up the `GITHUB_TOKEN` in this repo's settings>secrets.
2. I assume you will also hook it up in `pact-ruby-standalone` to dispatch trigger this one with the correct payload? (similar to how it's been done for `pact-node`)
3. It obviously hasn't been tested end to end because the current brew cask version matches pact-ruby-standalone's version.

**Comment by bethesque** [comment]
The GITHUB_TOKEN comes prepopulated by the action. You don't need to create a new one.

The dispatch is already wired up on the pact-ruby-standalone side https://github.com/pact-foundation/pact-ruby-standalone/blob/master/.github/workflows/release.yml#L49

**Comment by surpher** [comment]
Seems to be successfully triggering a new PR with every pact-ruby-standalone release. 👍 
Closing.
